### ISSUE TITLE
nvdimm-test: LIC_FILES_CHKSUM points to an invalid file

### ISSUE THREAD

**Issue by prakhya** [01org/luv-yocto#112]
I have seen a build failure (image attached) when I tried building LUV (after bumping kernel to v4.9). I tried to build LUV after deleting "build" directory.
![issue](https://cloud.githubusercontent.com/assets/10333447/21413875/7320a210-c7af-11e6-952c-2d3e2b5622b7.png)

**Comment by meghadey** [comment]
seen with recipes which depend on the kernel source as well(efivarfs-test)

**Comment by meghadey** [comment]
same issue as https://github.com/01org/luv-yocto/issues/106

**Comment by meghadey** [comment]
To Reproduce this issue (nvdimm-test): 
1. update the kernel(add/remove patches, add/remove cfg files)
2. Remove the tmp and sstate-cache dir
3. do a bitbake luv-live-image

From our analysis we see that the do_unpack task of any recipe deleted the source directory, when the source directory and the work directory are not the same. This is logical for standalone recipes who do not depend on other recipes to obtain their source, as this will ensure we get a fresh copy of the source whenever we built the recipe. However, for recipes which depend on other recipes for their source(eg, efivarfs-test and nvdimm-test depend on the kernel source), this causes problems.
With the kernel source deleted, these recipes have no way to reference the kernel files and hence we get various errors relating to some files in the kernel being missing which is required by the subsequent tasks of the recipe.

Hence, in the efivarfs-test recipe we ensure that the source directory is not being deleted during the do_unpack task. And the nvdimm-test, we do not execute the do_unpack task itself since we do not have any files which we would like to add to the source.

**Comment by ricardon** [comment]
Maybe it would be good to see if we can set do_fetch, do_unpack, do_patch
to [noexec] = "1"

**Comment by ricardon** [comment]
Perhaps this can help:
diff --git a/meta-luv/recipes-kernel/nvdimm/nvdimm-test.bb b/meta-luv/recipes-kernel/nvdimm/nvdimm-test.bb
index bd42536..7c5120b 100644
--- a/meta-luv/recipes-kernel/nvdimm/nvdimm-test.bb
+++ b/meta-luv/recipes-kernel/nvdimm/nvdimm-test.bb
@@ -21,3 +21,5 @@ do_install_prepend() {
 do_populate_lic[depends] += "virtual/kernel:do_populate_lic"
 
 RPROVIDES_${PN} = "kernel-module-libnvdimm"
+
+do_clean[dirs] = ""

**Comment by ricardon** [comment]
Fixed with the aforementioned commit.
