### ISSUE TITLE
Audio Feedback/Indicator

### ISSUE THREAD

**Issue by Manouchehri** [01org/luv-yocto#121]
On devices where the GPU/display isn't working properly, it would be helpful to run `beep` and play some sound through the speakers to let the user know that LUV is done.

Of course using netconsole is much better if possible, but on some devices it isn't too convenient. e.g. TBT/USB-C only MacBooks.

![img_20170411_005120](https://cloud.githubusercontent.com/assets/7232674/24895114/ac06149e-1e5c-11e7-8b6d-94c5922fc2e2.jpg)

**Comment by ricardon** [comment]
This is a great suggestion!

**Comment by gkammela** [comment]
@Manouchehri adding an audio indicator is not as trivial as it sounds, mainly because it requires lot of drivers including the gfx drivers (to support the playback)  which will increase the size of the luv-image. I can help you fix the issue you are facing with the display if you provide me some additional details.

**Comment by meghadey** [comment]
Closing this. IF required, we can re-open this issue
