### ISSUE TITLE
LUV tool "Results were not saved in storage media"

### ISSUE THREAD

**Issue by rabenson10** [01org/luv-yocto#50]
Is this a known issue? Results were not saved in storage media. I have a number of failures, but can't see the results.

**Comment by ricardon** [comment]
Hi! Many thanks for reporting your issue. There could be several factors impacting your experience. It could be that there was a problem when flashing the image. When LUV completed the tests, did you see the ""Results were saved in your boot media. You may now turn off the system and remove it." message or did you see "Results were not saved in storage media"

Also, it could that results were not displayed correctly in your development system. Did you use a Windows system? On Windows you will see only a "luv-results" partition. On Linux you should see also another "boot" partition.

**Comment by rabenson10** [comment]
It returned ""Results were not saved in storage media". I used a Ubuntu box to view the partitions and to make the drive from the image using DD. Are there permission issues (i.e chmod) that need to be applied for the log file to write?

**Comment by ricardon** [comment]
Hmm, it sounds to me that there was a problem when flashing the image. LUV will present that message when it cannot find the luv-results partition. Here is a snippet of the test manager code:

mountpoint -q ${LUV_STORAGE}
if [ $? -eq 0 ]; then
    umount ${LUV_STORAGE}
    SAVE_STATUS="Results were saved in your boot media. You may now turn off the system and remove it."
else
    SAVE_STATUS="Results were not saved in storage media."
fi

This partition is created when flashing the image. You don't need to set any permissions. One detail that has helped in the past is flashing LUV into /dev/sdX rather than into /dev/sdXN. For instance, if your USB stick was /dev/sdd and it had one partition you would need to do

dd if=luv.img of=/dev/sdd

and not

dd if=luv.img of=/dev/sdd1

You can take a look a this blog post for further details. The flashing process is discussed near the bottom.

http://firmware.intel.com/blog/luv-your-firmware-part-iii

I hope this helps!

PD. Sorry, I just realized that you put your error message at the title. My bad!

**Comment by rabenson10** [comment]
Hi Ricardo,
That did the trick. I should have known.... I've been working with other operating systems and it's been awhile since I worked on a Linux box. Thank you for spotting my error.

Regards,
Ron Benson (Intel Corporation)

**Comment by ricardon** [comment]
Excellent! Please let us know if run into more issues. :)
