### ISSUE TITLE
luv-live-v2.0-rc2 fails to boot on laptops with Insyde BIOSH2O

### ISSUE THREAD

**Issue by ghost** [01org/luv-yocto#60]
Two different laptops:

Toshiba Satellite L305: Gives error "This is not a bootable device. Please install a bootable floppy and press any key" 
    InsydeH2O setup utility version 3.5 reports system BIOS version 1.70

Acer Aspire 4810T: Hangs with blank screen, cursor blinking in home corner.
    InsydeH2O setup utility version 3.5 reports system BIOS version 1.10 KBC version 03.19
    message at boot reports "Insyde H2O EFI 2.0 MB"

**Comment by ricardon** [comment]
Thanks for the reports!

Could it be that the Toshiba Satellite L305 recognizes only GPT disks? This seems unlikely as most BIOS implementations support MBR as well. Is there a way to verify that you can see the two partitions in the USB stick. The bootable partition is the second one.

On the Acer model, it seems that the bootloader faills to run. Do by any chance have access to an EFI shell? If yes, would you mind to try to execute the file /EFI/BOOT/grubx64.efi? Boot regularly begins with /EFI/BOOT/bootx64.efi, which is the shim bootloader for secure boot.

Also, do you see any output on the serial console?

Thanks and BR,

**Comment by koanhead-fgsea** [comment]
Within the OS I can certainly see both partitions on the luv-live stick. I don't know how to invoke a UEFI shell if there's one available, nor yet how to find out if there's one available. This after a few hours' searching. 

As to the serial console, I'm not entirely sure I have the correct cables on hand to make it happen, but if I have them I'll try it tonight.

**Comment by ricardon** [comment]
Thanks for the update. Generally the firmware lists the two partitions when
you choose to boot from removable media or at least give a hint that it is
booting from USB.

The option for the EFI shell is generally found along with other boot
options such as boot from disk, removable media or network. It is usually
called EFI shell or EFI console. Sometimes you need to enable these options
to appear in the boot menu.

I will try to gather screenshots of how it looks like on other firmware
implementations.

**Comment by koanhead-fgsea** [comment]
>Generally the firmware lists the two partitions when you choose to boot from removable media or at least give a hint that it is booting from USB.

I would have expected as much, but after disabling 'Quiet Boot' in the BIOS options the Acer lists the devices on the SATA bus (hdd and optical drive) but no other devices and no partition information.

The Toshiba doesn't offer an option to disable 'Quiet Boot', and there's no such enumeration at boot. Interestingly, setting 'Legacy USB Support' to 'Disabled' makes the 'this is not a bootable device' warning go away, instead the machine boots into GRUB2 on the harddisk. 

>The option for the EFI shell is generally found along with other boot options

It doesn't appear in the BIOS options on either laptop, nor in the boot (F12) menu.

**Comment by ricardon** [comment]
On Mon, Aug 10, 2015 at 9:22 AM, koanhead-fgsea <notifications@github.com>
wrote:

> Generally the firmware lists the two partitions when you choose to boot
> from removable media or at least give a hint that it is booting from USB.
>
> I would have expected as much, but after disabling 'Quiet Boot' in the
> BIOS options the Acer lists the devices on the SATA bus (hdd and optical
> drive) but no other devices and no partition information.
>
I see. Perhaps there is an option that disable booting from removable
media?? If you have another USB stick lying around, does it see the
partitions?

> The Toshiba doesn't offer an option to disable 'Quiet Boot', and there's
> no such enumeration at boot. Interestingly, setting 'Legacy USB Support' to
> 'Disabled' makes the 'this is not a bootable device' warning go away,
> instead the machine boots into GRUB2 on the harddisk.
>

Hmm. I would have expected that this legacy option referred to MBR
partitions?

> The option for the EFI shell is generally found along with other boot
> options
>
> It doesn't appear in the BIOS options on either laptop, nor in the boot
> (F12) menu.
>
If you don't have access to an EFI shell, one more experiment is to make a
backup of the file EFI/BOOT/bootx64.efi and rename the file
EFI/BOOT/grubx64.efi as EFI/BOOT/bootx64.efi. This will bypass the shim
bootloader and boot directly to LUV GRUB2.

**Comment by koanhead-fgsea** [comment]
> Hmm. I would have expected that this legacy option referred to MBR partitions?

According to https://superuser.com/questions/303365/what-does-legacy-usb-mouse-support-in-a-bios-mean that option enables BIOS support for USB HID devices and causes them the emulate PS/2 devices for OS that don't have their own USB support. https://support.microsoft.com/en-us/kb/250635 talks about some interesting side-effects it had on Win98, including hanging on startup or shutdown. Probably not relevant here - these laptops aren't _that_ old! 
 
I did try renaming grubx64.efi -> bootx64.efi but the behavior of both units is unchanged. This is baffling to me since I've booted both these laptops with GRUB2 on this very stick. I'm going to read up on Debian EFI stuff and try to debootstrap an EFI-enabled minimal system on this stick and see if that boots. I'm thinking that if that works on another machine and not on the laptops then there's something to go on in finding the differences between the two.

I finally got round to checking whether the Toshiba can only recognize GPT disks, and it turns out that its HDD is MBR formatted, so there's that.

**Comment by ricardon** [comment]
Just wanted to check if you still see this bug. It came to my mind if you have UEFI Compatibility Support Module enabled in your UEFI firmware. It could be the cases that it interferes with purely native UEFI boot. Also, it might be possible that the GRUB that boots for you is was not built for UEFI but for BIOS.

Finally, I might have a patch that supports GPT rather than MBR. Would you be interested in giving it a try?

**Comment by ricardon** [comment]
Perhaps this could help? http://nmilosev.svbtle.com/booting-uefi-usb-stick-on-a-toshiba-laptop-insydeh20-bios

**Comment by koanhead-fgsea** [comment]
Thanks for the link! Will try that over the weekend.

**Comment by koanhead-fgsea** [comment]
As it turns out the link did not work: the BIOS setup on this lappy (L305-S5933) does not offer options to disable Fast Boot nor to enable Secure Boot. This is allegedly InsydeH20 Rev 3.5, though the options on offer differ from those visible in various screenies and such on the internets; I hear that there are ways to hack up this BIOS to reveal "hidden" menus but I'm disinclined to fuss with this proprietary garbage product. I might try to coreboot it later, but not until I've got another working laptop. This latter might happen in the next few weeks, as I'm getting in a stack of T60s to refurb and flash with Libreboot.

In the meantime I will continue testing with the desktop computer https://github.com/01org/luv-yocto/issues/61

**Comment by ricardon** [comment]
Just wanted to check if the v2.0 release image was of any help with this issue.

**Comment by meghadey** [comment]
We not provide GPT images which could help with UEFI BIOSes. 

Closing this issue for now, can be reopened if needed.
