### ISSUE TITLE
32 bit compile failing for LUV; grub needs refitting

### ISSUE THREAD

**Issue by edTaub** [01org/luv-yocto#63]
We are trying to compile LUV for IA32 and compile fails at grub step. Need to modify grub to use existing UEFI functions rather than current ad-hoc approach

**Comment by ricardon** [comment]
Thanks for the report Ed! Actually, we do need our own implementation to load, parse, and relocate images when UEFI secure boot is enabled because we don't write any certificates to the UEFI database. Hence, when we use the UEFI LoadImage call our images will fail to load because they are not trusted. We base our verification based on the shim bootloader (https://mjg59.dreamwidth.org/20303.html). We check the validity of the images using the protocol provided by this shim. 

The error seems to be on how we parse and treat 32-bit binaries.

**Comment by ricardon** [comment]
Support was implemented with this:
https://github.com/01org/luv-yocto/commit/e08f3f710e798f1e18552e217d00b66a27b480c6
https://github.com/01org/luv-yocto/commit/b0c2e90b88bfa1fe541ad0e41c404741116548ee
https://github.com/01org/luv-yocto/commit/c8fbfa8d275e4c584b2bb3fd7a2d4123c511fe01
https://github.com/01org/luv-yocto/commit/c25837a1f1f327c2eb088147e48be7e03aec5d7b
